version: '3.1'
services:
  postgres:
    image: postgres
    container_name: monkeyshop-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: super_secret
      POSTGRES_USER: monkey
      POSTGRES_DB: monkeyshop-db
