server:
  protocol: http
  host: 0.0.0.0
  port: 8080
  context: monkeyshop
  version: v1
storage:
  versionControl: true
  eraseDB: true
  host: postgres # PostgreSQL container specified in docker-compose.yaml
  db: monkeyshop-db
  schema: monkey_data
  port: 5432
  user: monkey
  poolSize: 4
monkeyShop:
  http:
    auth:
      basePath: /auth
      token: /token
      pwd: /pwd
      tokenExpiresInSec: 600
    user:
      basePath: /users
      getUsers: ""
      postUsers: ""
      getUser: /:userId
      patchUser: /:userId
      deleteUser: /:userId
    customer:
      basePath: /customers
      getCustomers: ""
      postCustomers: ""
      getCustomer: /:customerId
      patchCustomer: /:customerId
      patchCustomerImg: /:customerId/img
      deleteCustomer: /:customerId
